### ISSUE TITLE
How to connect to network using Manifold 2C

### ISSUE THREAD

**Issue by StancyMiller** [ZJU-FAST-Lab/FAST-Dynamic-Vision#1]
你好，我最近也在尝试使用妙算2C作为飞机的机载板，但是我用无线网卡不能连接到局域网上，请问你们怎么解决的妙算2C的无线连接问题，谢谢！！

**Comment by edmundwsy** [comment]
可能是无线网卡的驱动问题。我们使用的是 华硕 [USB-AC57](https://www.asus.com.cn/Networking-IoT-Servers/Adapters/All-series/USB-AC57/) 网卡，安装的是这个 [88x2bu](https://github.com/morrownr/88x2bu) 驱动。

**Comment by StancyMiller** [comment]
> 可能是无线网卡的驱动问题。我们使用的是 华硕 [USB-AC57](https://www.asus.com.cn/Networking-IoT-Servers/Adapters/All-series/USB-AC57/) 网卡，安装的是这个 [88x2bu](https://github.com/morrownr/88x2bu) 驱动。

好的谢谢，我尝试一下🙂
