### ISSUE TITLE
Greeting from an autor 

### ISSUE THREAD

**Issue by CharlChc** [ZJU-FAST-Lab/FAST-Dynamic-Vision#2]
Hi edmundwsy,

I have read your paper of FAST-Dynamic-Vision: Detection and Tracking Dynamic Objects with Event and Depth Sensing, and I appreciate your great job on motion compensation and dodging against dynamic objects . Could I know if your paper get accepted by IROS this year or not? If it did, would you mind publish the code as you said in the paper?

Best,
Charlie

**Comment by edmundwsy** [comment]
Hi Charlie,

Thanks for your nice greeting! 

Fortunately, our paper was accepted by IROS 2021. Therefore, we will make our codes open-source shortly.

Best regards,
Siyuan
