### ISSUE TITLE
Configuration of the UAV

### ISSUE THREAD

**Issue by Kevinlibaba** [ZJU-FAST-Lab/FAST-Dynamic-Vision#5]
Hey team, you guys have implemented an amazing work. I just have a question about the configuration of the UAV. Did the configuration same to [Fast-Drone-250](https://github.com/ZJU-FAST-Lab/Fast-Drone-250)?

**Comment by siyuanwu99** [comment]
No, it's slightly different from Fast-Drone-250. We use DJI F450 frame in our experiment. Motors are from T-motor but of a different type.

**Comment by Kevinlibaba** [comment]
Thanks Siyuan, do you have an instruction of this UAV like [assemble.pdf](https://github.com/ZJU-FAST-Lab/Fast-Drone-250/blob/main/assemble.pdf)? Or what's the setting of control configuration value(like step 17 in assemble.pdf) ?

**Comment by siyuanwu99** [comment]
You can refer to assemble.pdf and our paper for your own UAV. Most steps are same to Drone-250. You only need to change the drone frame and motors. You also need to pay more attention to the mounting position of your event camera. In our project, the camera is mounted underneath the frame. To protect the camera and support the drone, we made a tripod from carbon plates.

**Comment by Kevinlibaba** [comment]
Thanks for your kindly answer, I will have a try.
